// Generated by CoffeeScript 1.3.1
(function() {
  var A, a;

  A = (function() {

    A.name = 'A';

    function A() {}

    A.prototype.bar = function() {
      return alert("bar");
    };

    return A;

  })();

  a = new A();

  YouAreDaBomb(a, 'bar').before(function() {
    return alert("foo");
  });

  a.bar();

}).call(this);
